name: Azure PowerShell VM Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PowerShell
      uses: azure/powershell@v1
      with:
        inlineScript: ./create-vm.ps1
        azPSVersion: 'latest'
